### ISSUE TITLE
A runtime error in predicting essential matrix using weighted_8points

### ISSUE THREAD

**Issue by WallofWonder** [xinliu29/NCMNet#5]
I trained the network on multiple GPUs using `DataParallel`

This error always happens during training, and I've tried many times to find that the timing of this error is random

Here is the output during training

```bash
/home/zyf/code/NCMNet/code/transformations.py:1899: UserWarning: failed to import module _transformations
  warnings.warn("failed to import module %s" % name)
-------------------------Deep Essential-------------------------
Note: To combine datasets, use .
start training .....

  0%|                                               | 0/500000 [00:00<?, ?it/s]/home/zyf/code/NCMNet/code/ncmnet.py:55: UserWarning: torch.symeig is deprecated in favor of torch.linalg.eigh and will be removed in a future PyTorch release.
The default behavior has changed from using the upper triangular portion of the matrix by default to using the lower triangular portion.
L, _ = torch.symeig(A, upper=upper)
should be replaced with
L = torch.linalg.eigvalsh(A, UPLO='U' if upper else 'L')
and
L, V = torch.symeig(A, eigenvectors=True)
should be replaced with
L, V = torch.linalg.eigh(A, UPLO='U' if upper else 'L') (Triggered internally at  /opt/conda/conda-bld/pytorch_1639180593867/work/aten/src/ATen/native/BatchLinearAlgebra.cpp:2499.)
  e, v = torch.symeig(X[batch_idx, :, :].squeeze(), True)
  2%|▌                              | 9999/500000 [1:24:52<70:07:07,  1.94it/s]Saving best model with va_res = 0.15714285714285714
  4%|█▏                           | 19999/500000 [2:51:56<103:50:07,  1.28it/s]Saving best model with va_res = 0.20476190476190476
  4%|█▏                            | 20120/500000 [2:54:52<69:30:56,  1.92it/s]
Traceback (most recent call last):
  File "main.py", line 93, in <module>
    main(config)
  File "main.py", line 72, in main
    train(model, train_loader, valid_loader, config)
  File "/home/zyf/code/NCMNet/code/train.py", line 72, in train
    loss_vals = train_step(step, optimizer, model, match_loss, train_data)
  File "/home/zyf/code/NCMNet/code/train.py", line 18, in train_step
    logits, ys_ds, e_hat, y_hat, normed_features = model(xs, ys)
  File "/home/zyf/anaconda3/envs/NCMNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zyf/anaconda3/envs/NCMNet/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/zyf/anaconda3/envs/NCMNet/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/zyf/anaconda3/envs/NCMNet/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/zyf/anaconda3/envs/NCMNet/lib/python3.6/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/zyf/anaconda3/envs/NCMNet/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/zyf/anaconda3/envs/NCMNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zyf/code/NCMNet/code/ncmnet.py", line 537, in forward
    x2, y2, ws1, e_hat, norm_feat1 = self.ds_1(x_, y1)
  File "/home/zyf/anaconda3/envs/NCMNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zyf/code/NCMNet/code/ncmnet.py", line 514, in forward
    e_hat = weighted_8points(x_ds, w2)
  File "/home/zyf/code/NCMNet/code/ncmnet.py", line 84, in weighted_8points
    v = batch_symeig(XwX)
  File "/home/zyf/code/NCMNet/code/ncmnet.py", line 55, in batch_symeig
    e, v = torch.symeig(X[batch_idx, :, :].squeeze(), True)
RuntimeError: symeig_cpu: The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated eigenvalues (error code: 8).

```

**Comment by xinliu29** [comment]
Hello, we have already uploaded the 'environment.yml' file to show the runtime environment of our code. You can try changing the versions of Python or CUDA to resolve this issue. I hope this can be helpful to you.

**Comment by WallofWonder** [comment]
> 

I updated the versions of Pytorch and Python according to the `environment.yml` file. 
The CUDA version remains as it was, which is 11.6.
The code has now been running for hours without any errors.
It seems that your solution works.
I hope I can finish the training successfully.

**Comment by WallofWonder** [comment]
> Hello, we have already uploaded the 'environment.yml' file to show the runtime environment of our code. You can try changing the versions of Python or CUDA to resolve this issue. I hope this can be helpful to you.

I successfully trained it once, but as I trained it again, the same error is reported.😟

**Comment by xinliu29** [comment]
Is it convenient to email me your Wechat? I'll try to help you run it successfully if possible.

**Comment by WallofWonder** [comment]
> Is it convenient to email me your Wechat? I'll try to help you run it successfully if possible.

Sure. I've emailed you my Wechat. Thanks for your patience!😀
